# Generated by Django 3.2.9 on 2021-12-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='Email_id',
            field=models.CharField(default='abc@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
