# Generated by Django 3.2.9 on 2021-12-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_emp_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='Contact_No',
            field=models.CharField(default='9683276478', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='Location',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
